import{a as u,S as f,i as s}from"./assets/vendor-Bbadc3Tp.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const d="55227321-8aa875f9c6bbda7d6f4af2a1c",y="https://pixabay.com/api/";async function m(a){try{return(await u.get(y,{params:{key:d,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(t){throw console.error(t),t}}const c=document.querySelector(".gallery"),p=new f(".gallery a");function h(a){const t=a.map(r=>`
      <li>
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <p>Likes: ${r.likes} | Views: ${r.views} | Comments: ${r.comments} | Downloads: ${r.downloads}</p>
      </li>
    `).join("");c.innerHTML=t,p.refresh()}function g(){c.innerHTML=""}function L(){document.querySelector(".loader").style.display="block"}function w(){document.querySelector(".loader").style.display="none"}const l=document.querySelector(".form"),b=l.querySelector('input[name="search-text"]');l.addEventListener("submit",async a=>{a.preventDefault();const t=b.value.trim();if(!t){s.error({title:"Error",message:"Please enter a search term!"});return}g(),L();try{const r=await m(t);r.hits.length===0?s.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}):h(r.hits)}catch{s.error({title:"Error",message:"Something went wrong. Try again later!"})}finally{w()}});
//# sourceMappingURL=index.js.map
